### ISSUE TITLE
Add instructions to integrate pyswitcherv2 with homebridge

### ISSUE THREAD

**Issue by neta540** [sagilo/pyswitcherv2#13]
It will be great if there would be instructions on how to setup pyswitcherv2 to work with Homebridge.

Configuring pyswitcherv2 to work with homebridge (for Apple HomeKit integration) is easy, using [homebridge-cmdswitch2](https://www.npmjs.com/package/homebridge-cmdswitch2). 

To configure homebridge with pyswitcherv2, assuming it is installed in /opt/pyswitcherv2, you will need to:

1. Install homebridge-cmdswitch2 node module.
2. Add cmdswitch2 platform into homebridge config.json, with corresponding switcherv2 configuration. 
3. Restart homebridge.

```bash
sudo npm install -g homebridge-cmdswitch2
```

config.json snippet

```
{
  "platform": "cmdSwitch2",
  "name": "CMD Switch 2",
  "switches": [
    {
      "name": "Switcher v2",
      "on_cmd": "python /opt/pyswitcherv2/pyswitcherv2/switcher.py -m on",
      "off_cmd": "python /opt/pyswitcherv2/pyswitcherv2/switcher.py -m off",
      "state_cmd": "python /opt/pyswitcherv2/pyswitcherv2/switcher.py -m get_state | grep -i 'Device is: on'"
    }
  ]
}
```

**Comment by sagilo** [comment]
Thanks!
I've added a [new page](https://github.com/sagilo/pyswitcherv2/wiki/Using-cmdswitch2-for-configuring-pyswitcherv2-to-work-with-homebridge-(thanks-to-neta540)) to Wiki
