### ISSUE TITLE
Please rename executable file

### ISSUE THREAD

**Issue by TheBlackBush** [sagilo/pyswitcherv2#5]
Hi,

Can you please rename the executable file under the 'bin' folder to '**switcher**' instead of '_pyswitcherv2_'
only for more comfort when writing the commands

**Comment by sagilo** [comment]
IMHO this is too generic and the best practice is sticking to the package name.
You can however create a symlink with your favorite command.

**Comment by sagilo** [comment]
IMHO this is too generic and the best practice is sticking to the package name.
You can however create a symlink with your favorite command.

**Comment by TheBlackBush** [comment]
ok no problem, i'll create a symlink
