### ISSUE TITLE
can't find credentials file when running outside of the folder

### ISSUE THREAD

**Issue by TheBlackBush** [sagilo/pyswitcherv2#6]
Version: 1.2.6
When i try to run the script outside of the script folder' the script can't find the credentials file.

here are the results within the script folder:
```
BuSHari@DiskStation:/var/packages/python/target/lib/python2.7/site-packages/pyswitcherv2$ pyswitcherv2 -m get_state
2018-03-14 09:10:25
Connecting...
Connected
Sending local sign in request
Got local sign in response
Sending phone state request
Got phone state response
Device is: off
Closing socket...
```

here are the results when trying outside of script folder:
```
BuSHari@DiskStation:/var/packages/python/target$ pyswitcherv2 -m get_state
ERROR: Missing credentials file (credentials.json), run script in parse mode to generate from pcap file
```

**Comment by sagilo** [comment]
Already fixed in 64668013d5f9a8965f440a4c2461828ec71f2dc4

**Comment by TheBlackBush** [comment]
Thanks,
Can you please push it to master and pip server?

**Comment by sagilo** [comment]
It's on dev branch.
It will probably be merged in the next few days
You can provide the credentials file path by argument in the meantime (`-c/--credentials_file_path`)
